name: 'attribution_project'
version: '1.0.0'

profile: 'attribution_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]

macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  attribution_project:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
